version: '3.8'

x-args: &args
  args:
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  guinea-bot:
    image: ${REGISTRY}${REPOSITORY}guinea-bot:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      <<: *args
      target: guinea-bot
    env_file:
      - guinea-bot.env
    restart: unless-stopped
